### ISSUE TITLE
Makes campfires not work right

### ISSUE THREAD

**Issue by Aces-and-Jacks** [SchmarrnDevs/Lighty#17]
https://mclo.gs/EIqtjBL

**Comment by andi-makes** [comment]
Please provide further information:

- What about campfires is not working right and what are the minimal Mods and steps to reproduce this issue?

Just with Lighty campfires work like they should.

**Comment by Aces-and-Jacks** [comment]
https://mclo.gs/M807F5j

just with lighty and sodium

![2023-03-05_16 08 48](https://user-images.githubusercontent.com/106651342/222986220-cb02622f-81cd-4b24-bcbe-8345ec1a4bbe.png)
![2023-03-05_16 08 57](https://user-images.githubusercontent.com/106651342/222986225-a9e2904c-fbe2-4a1a-b2a2-43338dffa0bc.png)

makes the smoke stop working correctly

**Comment by andi-makes** [comment]
Thank you for providing extra information! The images are really helpful to understand the problem!

I was able to confirm that this also happens without sodium - I just didn't notice it immediately before.

It only happens with the Carpet Mode - probably some issue with how I am rendering this specific overlay.

I will look into it, I wanted to rewrite the way overlays get rendered anyways.
It will take some time though.

**Comment by andi-makes** [comment]
I've found the bug and fixed it - tomorrow when 1.19.4 is released I will backport the fix and make a new Lighty release for all supported versions.

**Comment by Aces-and-Jacks** [comment]
Ok. Thanks for the fix
