### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Aces-and-Jacks** [SchmarrnDevs/Lighty#2]
https://mclo.gs/aVbw8Of

Likely not compatible with accuratemaps

**Comment by andi-makes** [comment]
Could you please try to narrow it down to the minimum required mods to cause the crash? I tried it with just Lighty, Accuratemaps, fapi and fabric kotlin and couldn't reproduce the issue

**Comment by Aces-and-Jacks** [comment]
ok. might take a bit

**Comment by andi-makes** [comment]
while taking a further look at your crashlog, it seems like a mixin from the mod collective crashes, and there seems to [be an update for the mod addressing the issue](https://modrinth.com/mod/collective/version/1.19.2-5.2-fabric).

Are you certain Lighty is the cause of the crash? As in, does the instance launch without Lighty enabled?

**Comment by Aces-and-Jacks** [comment]
oops. My mistake forgot to check that after updating it. updated collective again and its all good now

**Comment by Aces-and-Jacks** [comment]
thanks
