### ISSUE TITLE
lighty-fabric-2.0.1+1.20.1 - Crashes over time when the overlay is enabled

### ISSUE THREAD

**Issue by UnIockables** [SchmarrnDevs/Lighty#25]
With the overlay enabled, the game starts to stutter more and more, before inevitably crashing. The crash report says there is insufficient memory for the Java Runtime Environment to continue. 
I tried increasing the RAM allocated for the fabric install to 6gb, but that did not solve the issue.
As well as Lighty, I am running fabric, fabric api, sodium, lithium, entityculling, iris, indium, continuity, and modmenu. When the mod is installed but the overlay is disabled the game runs without issues. 
This didn't happen with the previous version of the mod I used (1.19.3 version).
Happy to share more info if needed.

**Comment by andi-makes** [comment]
Thank you for reporting this issue!

I fixed it! (or at least I can no longer reproduce it with the changes I've made)

A new Lighty release with the fix applied will get published later today.

Again, thank you for reporting this bug and have fun!

**Comment by DionWillie** [comment]
@andi-makes This issue is also present in 1.20 version, lighty-2.0.0+1.20

**Comment by andi-makes** [comment]
@DionWillie published another release for 1.20
