### ISSUE TITLE
Wrong spots marked red/orange

### ISSUE THREAD

**Issue by MrAmericanMike** [SchmarrnDevs/Lighty#32]
I noticed that it looks like the mod only considers the light level, but it doesn't consider the blocks type.

For example, it's highlighting in red: Stairs, Leaves and many other non solid blocks.

It looks like it also gets confused with flowers.

![2023-07-07_20 17 54](https://github.com/SchmarrnDevs/Lighty/assets/8037559/b4447d1a-00cd-4976-aadb-75658947e82b)
![2023-07-07_20 18 09](https://github.com/SchmarrnDevs/Lighty/assets/8037559/0705f844-f352-4367-9628-1c593b400793)
![2023-07-07_20 23 29](https://github.com/SchmarrnDevs/Lighty/assets/8037559/4e6251fd-ecdf-4230-9916-f014bd3d1bf4)

**Comment by andi-makes** [comment]
thanks for the report–I didn't get around to really finishing the cross mode, and it just slipped into a release. For now, carpet mode should work like you'd expect. I'll look into fixing it today, should be rather trivial, and I'll probably release a new version later today

**Comment by andi-makes** [comment]
An updated version is available [on modrinth now](https://modrinth.com/mod/lighty), thank you again for reporting and have fun with the improved cross mode!
