### ISSUE TITLE
Ideas: New Modes

### ISSUE THREAD

**Issue by andi-makes** [SchmarrnDevs/Lighty#5]
I feel like an issue is the wrong place for ideas and suggestions. That's why I created [a GitHub Discussions thing](https://github.com/SchmarrnDevs/Lighty/discussions/) - feel free to post your ideas [in the Ideas and Suggestions category](https://github.com/SchmarrnDevs/Lighty/discussions/categories/ideas-and-suggestions)!

The original issue, for archiving purposes:

---

For example:
 - [x] Show Light Level Mode: Display the actual numbers, not only whether a Mob can spawn or not
 - [ ] Spawner Mode: Spawners require different light levels compared to normal spawns
 - [ ] Underwater/Air Spawn Areas: Could be helpful for Drowned or Ghasts/maybe Phantoms? Could one block Phantom spawns?
 - [ ] Mob filters: There are troubles with the spawn conditions only known to the server, but a workaround is possible.
 - [ ] Crop Light Level: Highlight farmland where the light level is not optimal

**Comment by MODKILLER1001** [comment]
I second the Show Light Level Mode to display the actual numbers. That seems like it would be the most helpful and easiest on your end.

**Comment by Capadillo** [comment]
>Show Light Level Mode: Display the actual numbers, not only whether a Mob can spawn or not

+1 Actual number would be exactly what I would want. Made toggle-able of course.
Main use in my case is for optimizing farmland light level.

**Comment by andi-makes** [comment]
Thanks for the Feedback @MODKILLER1001 and @Capadillo!

Soon I'll have time again to work on Lighty, and displaying the light level numbers will be the first thing I'll be working on.

There is something I'd love to hear your feedback on though - How to actually switch between the modes.
As there will be a few more modes in the future, I've been thinking of some kind of menu like the F3+F4 gamemode switcher, but it is toggled by F7 (or your mapped key), so you can release F7 again and then choose your desired mode with the mouse without needing to hold the button. I think this would be a kinda vanilla feeling way of doing this, but if any of you two (or others that may stumble across this issue) have another idea, feel free to share it! I'd highly appreciate your input!

**Comment by Capadillo** [comment]
> Thanks for the Feedback @MODKILLER1001 and @Capadillo!
> 
> Soon I'll have time again to work on Lighty, and displaying the light level numbers will be the first thing I'll be working on.
> 
> There is something I'd love to hear your feedback on though - How to actually switch between the modes. As there will be a few more modes in the future, I've been thinking of some kind of menu like the F3+F4 gamemode switcher, but it is toggled by F7 (or your mapped key), so you can release F7 again and then choose your desired mode with the mouse without needing to hold the button. I think this would be a kinda vanilla feeling way of doing this, but if any of you two (or others that may stumble across this issue) have another idea, feel free to share it! I'd highly appreciate your input!

Actually, I really like the concept you have suggested. So long as the selectable modes doesn't exceed 5-6 I think it would be manageable.

**Comment by andi-makes** [comment]
Hey @MODKILLER1001 and @Capadillo!

I've implemented the Number Mode - the GUI did change a little bit from what I had imagined, but this way it was easier to implement :D

I hope you have fun with this new feature! Now available [from Modrinth!](https://modrinth.com/mod/lighty)

**Comment by Alasofia** [comment]
I know it's super niche, but snapshot support! I run a snapshot server and it'd be great to have a mod like Lighty.
Trying my best to port it on my own but it's been years since I wrote Java.

**Comment by andi-makes** [comment]
Thanks for the feedback!

Supporting snapshots would be nice, *but* it is kind of a weekly commitment - I am just one person working on this at the moment, and I definitely don't have time for doing it every week - maybe I can do it most weeks, but I cannot guarantee anything.

I will have a look at it tomorrow, though! If you figure it out in the meantime, feel free to make a PR!

**Comment by Alasofia** [comment]
In my experience most changes between snapshots are only a recompile away from working between snapshots. I _think_ if someone gets it up to 23w03a/23w04a I could keep it up from there.

Couldn't figure it out myself yet, looks like something has changed in Screen and needs a bit of work.

Either way thanks for the work on 1.19.3, it's replaced Light Overlay in most of my packs :)

**Comment by andi-makes** [comment]
Lighty now supports 23w03a and 22w04a! [Now available at Modrinth!](https://modrinth.com/mod/lighty/version/UR2JD4Vq) Please read through the changelog for further information about how I want to handle snapshots for now, and thanks for using Lighty!

**Comment by andi-makes** [comment]
I feel like an issue is the wrong place for ideas and suggestions. That's why I created [a GitHub Discussions thing](https://github.com/SchmarrnDevs/Lighty/discussions/) - feel free to post your ideas [in the Ideas and Suggestions category](https://github.com/SchmarrnDevs/Lighty/discussions/categories/ideas-and-suggestions)!
