### ISSUE TITLE
Lighty indicators (any type) do not appear in rare circumstances

### ISSUE THREAD

**Issue by lagomoof** [SchmarrnDevs/Lighty#70]
Steps to reproduce:

1) Dig to y=32 somewhere away from natural light sources.

2) Place a torch on the right wall at head height.

3) Turn on Lighty's indicators

4) Dig ahead in a straight line for at least 15 blocks, standard 2x1 tunnel.

Note that, while digging, the indicators will appear on the later blocks at waist height, y=33, but never on the ground at y=32. At that position there should be at least three indicators.

The indicators can be forced to appear by: a) removing a block from the floor; b) placing and removing a torch; c) exiting the world and logging back on.

This happens in creative as well as survival. It happens on servers as well as in single-player.

It still happens with all other mods removed (with the exception of the absolute necessities, like fabric itself).

Version used: lighty-fabric-3.0.0-beta.3+1.21.jar

This may have happened at other y-levels, but I was not taking notes at the time.

EDIT: This seems to happen at y=16 and y=-32 as well. Haven't tested all multiples of 16, but it seems a safe bet.

**Comment by andi-makes** [comment]
Thank you for reporting this bug!

I was able to reproduce it, and it does indeed seem to happen at multiples of 16. This is a very interesting bug, I don't exactly know what causes it, but I'll investigate!

**Comment by andi-makes** [comment]
I've fixed it already, expect this to be resolved in the next release!

I'll leave this issue open until I release the next Lighty version.

Thanks again for reporting this bug, and many thanks for the great bug report!

**Comment by andi-makes** [comment]
Finally got around to releasing the fix with Lighty v3.0.0-beta.4, thank you for your patience and for reporting the issue!
