### ISSUE TITLE
Lightly wont load on server start up.

### ISSUE THREAD

**Issue by lzapatacon** [SchmarrnDevs/Lighty#73]
So I'm using a docker compose file to start my server, and everything is going ok until Lightly starts to load.
Here is my crash report.

https://mclo.gs/mgurjhd

**Comment by andi-makes** [comment]
Hi!

Because Lighty is a client side mod, you don't need to include it on the server. The easiest solution is to just remove Lighty from the server's mods folder. It is completely sufficient to have Lighty installed on just the client.

I hope this helps, and thanks for using Lighty!
