### ISSUE TITLE
[Suggestion] Add Forge support

### ISSUE THREAD

**Issue by Saksi83** [SchmarrnDevs/Lighty#77]

**Comment by andi-makes** [comment]
Currently, there are no plans for providing Forge support for the newest Minecraft versions. Lighty is available on NeoForge however, and when I feel like Lighty is "done", I might offer a Forge version again. For now, the main focus is on improving Lighty for the platforms it is available on, which might take some time to complete.

That said, if someone wants to PR Forge support, I'll gladly accept the PR if it fits into the existing project structure.

Then again, as far as I can tell most big mods are transitioning away from Forge to NeoForge, so maybe it is time to move on too.

**Comment by Saksi83** [comment]
Thank you for such a fast and elaborate answer.

I must admit, I was not aware of the Forge/NeoForge situation until I saw your answer. I totally get why you would want to put your efforts elsewhere
